// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticleTag = "article_tag"

// ArticleTag mapped from table <article_tag>
type ArticleTag struct {
	ArticleID int `gorm:"column:article_id;type:int;primaryKey" json:"article_id"`
	TagID     int `gorm:"column:tag_id;type:int;primaryKey" json:"tag_id"`
}

// TableName ArticleTag's table name
func (*ArticleTag) TableName() string {
	return TableNameArticleTag
}
