// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID            int       `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	IP            string    `gorm:"column:ip;type:varchar(255)" json:"ip"`
	Content       string    `gorm:"column:content;type:mediumtext" json:"content"`
	Province      string    `gorm:"column:province;type:varchar(100)" json:"province"`
	City          string    `gorm:"column:city;type:varchar(100)" json:"city"`
	ExamineStatus int       `gorm:"column:examine_status;type:tinyint;not null;default:1;comment:审核状态:0未通过1通过" json:"examine_status"` // 审核状态:0未通过1通过
	ArticleID     int       `gorm:"column:article_id;type:int" json:"article_id"`
	CommentID     int       `gorm:"column:comment_id;type:int" json:"comment_id"`
	Creator        int       `gorm:"column:creator;type:int" json:"creator"`
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	User          User     `gorm:"foreignKey:Creator" json:"user"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
