// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSite = "site"

// Site mapped from table <site>
type Site struct {
	ID            int       `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name          string    `gorm:"column:name;type:varchar(255)" json:"name"`
	ProvinceCode  int       `gorm:"column:province_code;type:int" json:"province_code"`
	CityCode      int       `gorm:"column:city_code;type:int" json:"city_code"`
	AddressDetail string    `gorm:"column:address_detail;type:varchar(255)" json:"address_detail"`
	Images        string    `gorm:"column:images;type:text" json:"images"`
	Desc          string    `gorm:"column:desc;type:varchar(255)" json:"desc"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Creator       int       `gorm:"column:creator;type:int" json:"creator"`
}

// TableName Site's table name
func (*Site) TableName() string {
	return TableNameSite
}
