// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int       `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Username  string    `gorm:"column:username;type:varchar(255);not null" json:"username"`
	Password  string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Nickname  string    `gorm:"column:nickname;type:varchar(255)" json:"nickname"`
	Avatar    string    `gorm:"column:avatar;type:varchar(255)" json:"avatar"`
	Desc      string    `gorm:"column:desc;type:varchar(255)" json:"desc"`
	Email     string    `gorm:"column:email;type:varchar(255)" json:"email"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Role      int       `gorm:"column:role;type:int;default:2;comment:1管理员2普通用户" json:"role"` // 1管理员2普通用户
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
